plugins:
    - search
    - mermaid2
extra_javascript:
    - https://unpkg.com/mermaid/dist/mermaid.min.js
site_name: POC
nav:
    - Home: index.md
    - Arquitetura: arq.md
    - About: about.md
theme:
  name: material
  palette:
    primary: deep purple
    accent: deep purple