plugins:
    - search
    - mermaid2
extra_javascript:
    - https://unpkg.com/mermaid/dist/mermaid.min.js
site_name: POC
nav:
    - Home: index.md
    - Arquitetura: 
        - Diagrama: arq.md
        - Extração: ext.md
    - About: about.md
    - Tasks: 
        - Filter New Missions: filter_new_missions.md
# theme:
#   name: material
#   palette:
#     primary: deep purple
#     accent: deep purple