theme:
    name: mkdocs
    nav_style: hsl(300, 50%, 40%)
extra_css:
  - stylesheets/extra.css
#   - https://unpkg.com/mermaid@7.1.2/dist/mermaid.css
markdown_extensions:
    - attr_list
    - pymdownx.superfences:
        custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_div_format
plugins:
    - search
    - mermaid2
extra_javascript:
    - https://unpkg.com/mermaid/dist/mermaid.min.js
site_name: POC
nav:
    - Home: index.md
    - Arquitetura: 
        - Diagrama: arq.md
        - Extração: ext.md
    - About: about.md
    - Tasks: 
        - Filter New Missions: filter_new_missions.md